- name: "Validate Nginx configuration"
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false
  tags:
    - deploy
    - destroy

- name: "Reload Nginx"
  service: name=nginx state=reloaded
  tags:
    - deploy
    - destroy