- hosts: destination
  become: true

  roles:
    - role: staging2
      static_staging: true
      domains:
        # Base domain
        - name: "~"
          tls_generate: true
          locations:
            - location: "/"
              port_name: "FRONTEND"
        # Subdomain
        - name: "sub.~"
          tls_enabled:
            tls_fullchain: "/full/path/to/exists/tls/fullchain/for/this/domain"
            tls_key: "/full/path/to/exists/tls/key/for/this/domain"
          locations:
            - location: "/"
              port_name: "SUBDOMAIN"
