- hosts: destination
  become: true

  roles:
    - role: staging2
      static_staging: true
      tls_generate: true
      base_auth:
        username: "111"
        password: "123"
      domains:
        # Base domain
        - name: "~"
          locations:
            - location: "/"
              port_name: "FRONTEND"
        # Subdomain
        - name: "sub.~"
          locations:
            - location: "/"
              port_name: "SUBDOMAIN"