- hosts: destination
  become: true

  roles:
    - role: staging2
      static_staging: true
      tls_generate: true
      domains:
        # Base domain
        - name: "~"
          base_auth:
            username: "111"
            password: "123"
          locations:
            - location: "/"
              proxy_pass: "example.com"
              proxy_header_disabled: true
        # Subdomain
        - name: "sub.~"
          locations:
            - location: "/"
              proxy_pass: "yandex.com"
              proxy_header_disabled: false
              proxy_proto: "https"
              proxy_timeout: 600