- hosts: destination
  become: true

  roles:
    - role: staging2
      static_staging: true
      register_domain_name: true
      deploy_third_domain: true
      yandex_pdd_oauth_token: "your yandex pdd token"
      base_domain_name: "another-one-domain.ru"
      domains:
        - name: "~"
          locations:
            - location: "/"
              port_name: "NGINX"